# Generated by Django 2.1.2 on 2018-12-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0003_drawingmodel_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawingmodel',
            name='title',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
