# Generated by Django 2.1.2 on 2018-12-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0005_drawingmodel_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingmodel',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
