# Generated by Django 2.1.2 on 2018-12-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0006_drawingmodel_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingmodel',
            name='drawing_base64',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
