# Generated by Django 2.1.2 on 2018-12-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y%m%d/'),
        ),
    ]
