# Generated by Django 2.1.2 on 2018-12-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='icon',
            field=models.FilePathField(blank=True, null=True, verbose_name='/Users/kyutatsu/MyProjects/diarySite/media'),
        ),
    ]
