# Generated by Django 2.1.2 on 2018-12-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20181216_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='self_introduction',
            field=models.TextField(blank=True, help_text='255文字以内', max_length=255, null=True),
        ),
    ]
