# Generated by Django 2.1.2 on 2019-01-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_auto_20181216_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='icon',
            field=models.FilePathField(blank=True, null=True, verbose_name='/Users/kyutatsu/MyProjects/diaryForDeploy/diarySite/media/'),
        ),
    ]
